version: 0.2

env:
  variables:
    AWS_REGION: "us-east-1"
    FRONTEND_REPO: "devops-capstone-frontend"
    BACKEND_REPO: "devops-capstone-backend"

phases:
  pre_build:
    commands:
      - echo "Logging in to Amazon ECR..."
      - AWS_ACCOUNT_ID=$(echo "$CODEBUILD_BUILD_ARN" | cut -f 5 -d ':')
      - ECR_REGISTRY_URI="$AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com"
      - aws ecr get-login-password --region "$AWS_REGION" | docker login --username AWS --password-stdin "$ECR_REGISTRY_URI"
      - IMAGE_TAG="$CODEBUILD_BUILD_NUMBER"
      - echo "IMAGE_TAG=$IMAGE_TAG"
      - echo "ECR_REGISTRY_URI=$ECR_REGISTRY_URI"

  build:
    commands:
      - echo "Build & push frontend..."
      - docker build -t "$FRONTEND_REPO:$IMAGE_TAG" ./frontend
      - docker tag "$FRONTEND_REPO:$IMAGE_TAG" "$ECR_REGISTRY_URI/$FRONTEND_REPO:$IMAGE_TAG"
      - docker tag "$FRONTEND_REPO:$IMAGE_TAG" "$ECR_REGISTRY_URI/$FRONTEND_REPO:latest"
      - docker push "$ECR_REGISTRY_URI/$FRONTEND_REPO:$IMAGE_TAG"
      - docker push "$ECR_REGISTRY_URI/$FRONTEND_REPO:latest"

      - echo "Build & push backend..."
      - docker build -t "$BACKEND_REPO:$IMAGE_TAG" ./backend
      - docker tag "$BACKEND_REPO:$IMAGE_TAG" "$ECR_REGISTRY_URI/$BACKEND_REPO:$IMAGE_TAG"
      - docker tag "$BACKEND_REPO:$IMAGE_TAG" "$ECR_REGISTRY_URI/$BACKEND_REPO:latest"
      - docker push "$ECR_REGISTRY_URI/$BACKEND_REPO:$IMAGE_TAG"
      - docker push "$ECR_REGISTRY_URI/$BACKEND_REPO:latest"

  post_build:
    commands:
      - echo "Generating imagedefinitions artifacts for ECS deploy..."
      - rm -f imagedefinitions-frontend.json imagedefinitions-backend.json

      # IMPORTANT: "name" MUST match the container name in the target task definition
      - printf '[{"name":"frontend","imageUri":"%s"}]' "$ECR_REGISTRY_URI/$FRONTEND_REPO:$IMAGE_TAG" > imagedefinitions-frontend.json
      - printf '[{"name":"backend","imageUri":"%s"}]' "$ECR_REGISTRY_URI/$BACKEND_REPO:$IMAGE_TAG" > imagedefinitions-backend.json

      - echo "--- imagedefinitions-frontend.json ---"
      - cat imagedefinitions-frontend.json
      - echo "--- imagedefinitions-backend.json ---"
      - cat imagedefinitions-backend.json

artifacts:
  files:
    - imagedefinitions-frontend.json
    - imagedefinitions-backend.json
  discard-paths: yes
